### ISSUE TITLE
Submit package to Sublime Package Control

### ISSUE THREAD

**Issue by julianvmodesto** [caddyserver/sublimetext#2]
https://packagecontrol.io/docs/submitting_a_package

**Comment by mholt** [comment]
This is a good idea. Has anyone done this before? I'd like to make sure I get it right. :smile: Should the package info (manifest) file go in this repo?

**Comment by mholt** [comment]
PR submitted: https://github.com/wbond/package_control_channel/pull/6580

**Comment by mholt** [comment]
Added! https://github.com/wbond/package_control_channel/pull/6585

Pinging all who +1'ed this, for convenience: @tobz-nz @christiannaths @kujenga @augustoroman @Zhomart @LoikRevillon

You can now install this with Package Control.
