### ISSUE TITLE
First line is always variable.other.Caddyfile

### ISSUE THREAD

**Issue by willstott101** [caddyserver/sublimetext#4]
I believe this is making the assumption that the first line is always a site / port but that's not necessarily the case. Especially when creating a file to be imported by another.

This Caddyfile looks great in this syntax.
```
# Example local http service
:80

file_server
```

But this Caddyfile gives the first directive the wrong scope.
```
# Example file server snippet
file_server
```

**Comment by mholt** [comment]
> I believe this is making the assumption that the first line is always a site / port but that's not necessarily the case.

Actually, that is _always_ the case (in Caddy 1, which is all this extension supports). The Caddyfile always starts with the site address.

**Comment by willstott101** [comment]
Ok, well would you be willing to accept a PR which adds support for Caddy 2? Either as a separate syntax or just an update of the existing one

**Comment by mholt** [comment]
Absolutely! We can replace the existing one, Caddy 1 isn't supported anymore.
